### PR TITLE
Extracted ValueFormatter

### PR DESCRIPTION
**Pull request by szymach**

### CODE REVIEW

**Comment by szymach** [comment]
@fsi-open

**Comment by szymach** [comment]
This is required so it may be used in the new Translatable extension for DataGrid

**Comment by szymach** [comment]
@fsi-open

**Comment by szymach** [comment]
@fsi-open

**Review by chives — APPROVED** [review]

**Comment by szymach** [comment]
@rn0

**Review by rn0 — APPROVED** [review]

**Pull request merged**
